[book]
authors = ["Jonathan Sharman"]
language = "en"
multilingual = false
src = "src"
title = "Najan"

[preprocessor.najan]
command = "mdbook-najan lexicon.yaml"

[output.html]
additional-css = ["src/najan.css"]
curly-quotes = true
